### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JarneClauw** [JarneClauw/setup#1]
# TODO
Things i would like to do !

## Dotfiles
- [x] Git
- [x] Alacritty
- [ ] Neovim
- [ ] Spicetify
- [x] Zsh
- [ ] Starship (only languages setup left)
- [ ]  ...

## NixOS
- [x] Daily and weekly backups
- [x] ClamAV setup
- [ ] Atlas setup
- [x] Sops-nix
- [x] DevShells

## Other
- [x] Uploading wallpapers and profile pictures
